In [4]:
import numpy as np



In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b = np.array([[9,3,5,3],[3,5,6,7]])
print(b)

[[9 3 5 3]
 [3 5 6 7]]


In [17]:
# Get dimension
a.ndim
#b.ndim

1

In [10]:
# Get shape
a.shape
b.shape

(2, 4)

In [12]:
# Get type
a.dtype
b.dtype

dtype('int32')

In [13]:
# Get size
a.itemsize

4

In [16]:
# Get total size
a.size*a.itemsize
a.nbytes

12

In [18]:
print(a[0])

1


# Accessing and changing specific elements,rows, columns


In [20]:
a = np.array([[1,2,3,4,6,7],[8,9,10,11,12,13]])
print(a)

[[ 1  2  3  4  6  7]
 [ 8  9 10 11 12 13]]


In [22]:
# Get a specific element[r,c]
a[1,5]

13

In [23]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 6, 7])

In [24]:
# Get a specific collumn
a[: ,2]

array([ 3, 10])

In [26]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 7])

In [27]:
a[1,4]

12

In [28]:
# 3-d example
b= np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [30]:
b[0,2,1]

6

# Initializing different types of arrays

In [33]:
# All 0s matrix
np.zeros((4,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [35]:
# All1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [36]:
# Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [37]:
# The identity matrix 
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Mathematics

In [38]:
a = np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [39]:
a + 2

array([3, 4, 5, 6])

In [40]:
a * 2

array([2, 4, 6, 8])

In [41]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [42]:
b=np.array([1,0,1,0])
print(b)

[1 0 1 0]


In [43]:
a + b

array([2, 2, 4, 4])

In [44]:
a * b

array([1, 0, 3, 0])

In [45]:
# Take the sim
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [46]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# Linear Algebra

In [50]:
a = np.ones((2,3,))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])